# DevDashboard golangci-lint minimal v2 configuration
version: "2"

run:
  timeout: 3m
  tests: true

formatters:
  enable:
    - gofmt
    - goimports
  settings: {}

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
  settings:
    staticcheck:
      checks:
        - all
    revive:
      rules:
        - name: exported
        - name: package-comments

output:
  formats:
    text:
      colors: true
