# DevDashboard golangci-lint configuration
# Version 2.6.1+ compatible configuration
# See https://golangci-lint.run/usage/configuration/ for reference

version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
    - ineffassign
    - unused
    - misspell

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
