# DevDashboard golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/ for reference
version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
    - ineffassign
    - unused
    - misspell

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  staticcheck:
    checks: ["all"]

  revive:
    rules:
      - name: exported
        severity: warning
      - name: package-comments
        severity: warning
      - name: var-naming
        severity: warning

  errcheck:
    check-type-assertions: false
    check-blank: false

  misspell:
    locale: US

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

output:
  formats:
    text:
      path: stdout
  uniq-by-line: true
  sort-results: true
